#docker-compose up
version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDBF
    image: postgres
    environment:
      POSTGRES_DB: "local_db_film"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5433:5432"
